FROM python:3.9.6-alpine

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE djangodocker.settings
ENV DEBUG 1
ENV SECRET_KEY foo
ENV DJANGO_ALLOWED_HOSTS localhost
ENV SQL_ENGINE django.db.backends.postgresql
ENV SQL_DATABASE django
ENV SQL_USER django
ENV SQL_PASSWORD password
ENV SQL_HOST db
ENV SQL_PORT 5432
ENV DATABASE postgres


# install psycopg2 dependencies
RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy entrypoint.sh
COPY ./entrypoint.sh .
RUN sed -i 's/\r$//g' /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

# copy project
COPY . .

# run entrypoint.sh
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]